name: ci

on:
  workflow_dispatch:
  push:
    branches:
      - dev

jobs:

  ci-vipc:
    uses: vipm-io/OpenG-Tookit/.github/workflows/ci-container.yml@0438df1e7b574ea44725b72e34b11edb2e2f6c45
    secrets: inherit
